
include(Abytek/Utilities/SetGlobal)

if(ABYTEK_EBT_ENVIRONMENT_DEVELOPMENT_MAX_OPTIMIZED OR ABYTEK_EBT_ENVIRONMENT_COOKED_MAX_OPTIMIZED)
    Abytek_SetGlobal(ABYTEK_ENABLE_MAX_OPTIMIZATION ON)
else()
    Abytek_SetGlobal(ABYTEK_ENABLE_MAX_OPTIMIZATION OFF)
endif()

option(ABYTEK_AUTO_OPTIMIZATION_FLAGS ON)