
include(Abytek/Utilities/CommonFlags)

if(ANDROID)
    Abytek_SetGlobal(ABYTEK_ENABLE_SOCKET_IO_CLIENT OFF)
else()
    Abytek_SetGlobal(ABYTEK_ENABLE_SOCKET_IO_CLIENT ON)
endif()

if(ABYTEK_EBT_ENVIRONMENT_DEVELOPMENT OR ABYTEK_EBT_ENVIRONMENT_DEVELOPMENT_MAX_OPTIMIZED)
    Abytek_SetGlobal(ABYTEK_ENABLE_DEVELOPMENT_BUILD ON)
else()
    Abytek_SetGlobal(ABYTEK_ENABLE_DEVELOPMENT_BUILD OFF)
endif()

Abytek_SetGlobal(ABYTEK_ENABLE_DEVELOPMENT_DATA ${ABYTEK_ENABLE_DEVELOPMENT_BUILD})
if(NOT ABYTEK_ENABLE_SOCKET_IO_CLIENT)
    Abytek_SetGlobal(ABYTEK_ENABLE_DEVELOPMENT_DATA OFF)
endif()