
include(Abytek/Utilities/SetGlobal)



if(MSVC)
    Abytek_SetGlobal(ABYTEK_INSTRUCTION_EXTENSION_FLAG_SSE "/arch:SSE")
    Abytek_SetGlobal(ABYTEK_INSTRUCTION_EXTENSION_FLAG_SSE2 "/arch:SSE2")
    Abytek_SetGlobal(ABYTEK_INSTRUCTION_EXTENSION_FLAG_AVX "/arch:AVX")
    Abytek_SetGlobal(ABYTEK_INSTRUCTION_EXTENSION_FLAG_AVX2 "/arch:AVX2")
elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    Abytek_SetGlobal(ABYTEK_INSTRUCTION_EXTENSION_FLAG_SSE "-msse")
    Abytek_SetGlobal(ABYTEK_INSTRUCTION_EXTENSION_FLAG_SSE2 "-msse2")
    Abytek_SetGlobal(ABYTEK_INSTRUCTION_EXTENSION_FLAG_SSE3 "-msse3")
    Abytek_SetGlobal(ABYTEK_INSTRUCTION_EXTENSION_FLAG_SSE4 "-msse4")
    Abytek_SetGlobal(ABYTEK_INSTRUCTION_EXTENSION_FLAG_AVX "-mavx")
    Abytek_SetGlobal(ABYTEK_INSTRUCTION_EXTENSION_FLAG_AVX2 "-mavx2")
    Abytek_SetGlobal(ABYTEK_INSTRUCTION_EXTENSION_FLAG_FMA3 "-march=native")
    Abytek_SetGlobal(ABYTEK_INSTRUCTION_EXTENSION_FLAG_ARM_NEON "-mfpu=neon")
elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU")
    Abytek_SetGlobal(ABYTEK_INSTRUCTION_EXTENSION_FLAG_SSE "-msse")
    Abytek_SetGlobal(ABYTEK_INSTRUCTION_EXTENSION_FLAG_SSE2 "-msse2")
    Abytek_SetGlobal(ABYTEK_INSTRUCTION_EXTENSION_FLAG_SSE3 "-msse3")
    Abytek_SetGlobal(ABYTEK_INSTRUCTION_EXTENSION_FLAG_SSE4 "-msse4")
    Abytek_SetGlobal(ABYTEK_INSTRUCTION_EXTENSION_FLAG_AVX "-mavx")
    Abytek_SetGlobal(ABYTEK_INSTRUCTION_EXTENSION_FLAG_AVX2 "-mavx2")
    Abytek_SetGlobal(ABYTEK_INSTRUCTION_EXTENSION_FLAG_FMA3 "-mfma")
    Abytek_SetGlobal(ABYTEK_INSTRUCTION_EXTENSION_FLAG_ARM_NEON "-mfpu=neon")
else()
    message(FATAL_ERROR "<Abytek::Utilities::SIMDCompilerFlags> Unknown compiler; can't apply SIMD compiler flags.")
endif()