#include "Abytek/DirectX12/RHIConversionUtilities.hpp"


#ifdef ABYTEK_ENGINE_RHI_ENABLE_DIRECTX12
namespace Abytek
{
    ABYTEK_DEFINE_OBJECT_SINGLETON_CRT(F_DirectX12RHIConversionUtilities);

    ABYTEK_RA_OBJECT_DEFAULT(F_DirectX12RHIConversionUtilities);
    void F_DirectX12RHIConversionUtilities::Build()
    {
        A_RAObject::BuildMinimal();

        ABYTEK_BIND_OBJECT_SINGLETON_CRT();

        _GenerateD3D12SupportedFilterMap();
    }
    void F_DirectX12RHIConversionUtilities::Release()
    {
        _D3D12SupportedFilterMap = {};
        
        A_RAObject::Release();
    }

#define ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(InMinFilter, InMagFilter, InMipFilter, InFilterReductionType, Value) \
            { \
                F_D3D12InputForFilterConversion InputForFilterConversion; \
                InputForFilterConversion.MinFilter = E_RHITextureFilter::InMinFilter; \
                InputForFilterConversion.MagFilter = E_RHITextureFilter::InMagFilter; \
                InputForFilterConversion.MipFilter = E_RHITextureFilter::InMipFilter; \
                InputForFilterConversion.FilterReductionType = E_RHITextureFilterReductionType::InFilterReductionType; \
                _D3D12SupportedFilterMap[InputForFilterConversion] = Value; \
            }
    void F_DirectX12RHIConversionUtilities::_GenerateD3D12SupportedFilterMap()
    {
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(NEAREST, NEAREST, NEAREST, STANDARD, D3D12_FILTER_MIN_MAG_MIP_POINT );
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(NEAREST, NEAREST, LINEAR, STANDARD, D3D12_FILTER_MIN_MAG_POINT_MIP_LINEAR);
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(NEAREST, LINEAR, NEAREST, STANDARD, D3D12_FILTER_MIN_POINT_MAG_LINEAR_MIP_POINT );
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(NEAREST, LINEAR, LINEAR, STANDARD, D3D12_FILTER_MIN_POINT_MAG_MIP_LINEAR );
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(LINEAR, NEAREST, NEAREST, STANDARD, D3D12_FILTER_MIN_LINEAR_MAG_MIP_POINT );
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(LINEAR, NEAREST, LINEAR, STANDARD, D3D12_FILTER_MIN_LINEAR_MAG_POINT_MIP_LINEAR );
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(LINEAR, LINEAR, NEAREST, STANDARD, D3D12_FILTER_MIN_MAG_LINEAR_MIP_POINT );
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(LINEAR, LINEAR, LINEAR, STANDARD, D3D12_FILTER_MIN_MAG_MIP_LINEAR );
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(ANISOTROPIC, ANISOTROPIC, NEAREST, STANDARD, D3D12_FILTER_MIN_MAG_ANISOTROPIC_MIP_POINT);
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(ANISOTROPIC, ANISOTROPIC, ANISOTROPIC, STANDARD, D3D12_FILTER_ANISOTROPIC );
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(NEAREST, NEAREST, NEAREST, COMPARE, D3D12_FILTER_COMPARISON_MIN_MAG_MIP_POINT );
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(NEAREST, NEAREST, LINEAR, COMPARE, D3D12_FILTER_COMPARISON_MIN_MAG_POINT_MIP_LINEAR );
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(NEAREST, LINEAR, NEAREST, COMPARE, D3D12_FILTER_COMPARISON_MIN_POINT_MAG_LINEAR_MIP_POINT );
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(NEAREST, LINEAR, LINEAR, COMPARE, D3D12_FILTER_COMPARISON_MIN_POINT_MAG_MIP_LINEAR );
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(LINEAR, NEAREST, NEAREST, COMPARE, D3D12_FILTER_COMPARISON_MIN_LINEAR_MAG_MIP_POINT );
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(LINEAR, NEAREST, LINEAR, COMPARE, D3D12_FILTER_COMPARISON_MIN_LINEAR_MAG_POINT_MIP_LINEAR);
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(LINEAR, LINEAR, NEAREST, COMPARE, D3D12_FILTER_COMPARISON_MIN_MAG_LINEAR_MIP_POINT );
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(LINEAR, LINEAR, LINEAR, COMPARE, D3D12_FILTER_COMPARISON_MIN_MAG_MIP_LINEAR );
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(ANISOTROPIC, ANISOTROPIC, NEAREST, COMPARE, D3D12_FILTER_COMPARISON_MIN_MAG_ANISOTROPIC_MIP_POINT);
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(ANISOTROPIC, ANISOTROPIC, ANISOTROPIC, COMPARE, D3D12_FILTER_COMPARISON_ANISOTROPIC );
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(NEAREST, NEAREST, NEAREST, MIN, D3D12_FILTER_MINIMUM_MIN_MAG_MIP_POINT );
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(NEAREST, NEAREST, LINEAR, MIN, D3D12_FILTER_MINIMUM_MIN_MAG_POINT_MIP_LINEAR );
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(NEAREST, LINEAR, NEAREST, MIN, D3D12_FILTER_MINIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT );
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(NEAREST, LINEAR, LINEAR, MIN, D3D12_FILTER_MINIMUM_MIN_POINT_MAG_MIP_LINEAR );
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(LINEAR, NEAREST, NEAREST, MIN, D3D12_FILTER_MINIMUM_MIN_LINEAR_MAG_MIP_POINT );
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(LINEAR, NEAREST, LINEAR, MIN, D3D12_FILTER_MINIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR );
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(LINEAR, LINEAR, NEAREST, MIN, D3D12_FILTER_MINIMUM_MIN_MAG_LINEAR_MIP_POINT );
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(LINEAR, LINEAR, LINEAR, MIN, D3D12_FILTER_MINIMUM_MIN_MAG_MIP_LINEAR );
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(ANISOTROPIC, ANISOTROPIC, NEAREST, MIN, D3D12_FILTER_MINIMUM_MIN_MAG_ANISOTROPIC_MIP_POINT );
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(ANISOTROPIC, ANISOTROPIC, ANISOTROPIC, MIN, D3D12_FILTER_MINIMUM_ANISOTROPIC );
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(NEAREST, NEAREST, NEAREST, MAX, D3D12_FILTER_MAXIMUM_MIN_MAG_MIP_POINT );
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(NEAREST, NEAREST, LINEAR, MAX, D3D12_FILTER_MAXIMUM_MIN_MAG_POINT_MIP_LINEAR );
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(NEAREST, LINEAR, NEAREST, MAX, D3D12_FILTER_MAXIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT );
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(NEAREST, LINEAR, LINEAR, MAX, D3D12_FILTER_MAXIMUM_MIN_POINT_MAG_MIP_LINEAR );
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(LINEAR, NEAREST, NEAREST, MAX, D3D12_FILTER_MAXIMUM_MIN_LINEAR_MAG_MIP_POINT );
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(LINEAR, NEAREST, LINEAR, MAX, D3D12_FILTER_MAXIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR );
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(LINEAR, LINEAR, NEAREST, MAX, D3D12_FILTER_MAXIMUM_MIN_MAG_LINEAR_MIP_POINT );
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(LINEAR, LINEAR, LINEAR, MAX, D3D12_FILTER_MAXIMUM_MIN_MAG_MIP_LINEAR );
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(ANISOTROPIC, ANISOTROPIC, NEAREST, MAX, D3D12_FILTER_MAXIMUM_MIN_MAG_ANISOTROPIC_MIP_POINT);
        ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER(ANISOTROPIC, ANISOTROPIC, ANISOTROPIC, MAX, D3D12_FILTER_MAXIMUM_ANISOTROPIC );
    }
#undef ABYTEK_INTERNAL_ADD_D3D12_TEXTURE_FILTER
}
#endif