#pragma once

__exported import Abytek.ECMS.SRPInstancedMeshletBuffer_ECMS;

#define ABYTEK_SRP_ECMS_GET_INSTANCED_MESHLET_BUFFER(Name) ___Abytek_SRP_ECMS_InstancedMeshletBuffer_##Name
#define ABYTEK_SRP_ECMS_GET_INSTANCED_MESHLET_WRITE_OFFSET_BUFFER(Name) ___Abytek_SRP_ECMS_InstancedMeshletWriteOffsetBuffer_##Name

#define ABYTEK_SRP_ECMS_DEFINE_INSTANCED_MESHLET_BUFFER_RO(Name) \
    StructuredBuffer<Abytek::SRP::ECMS::F_InstancedMeshlet> ABYTEK_SRP_ECMS_GET_INSTANCED_MESHLET_BUFFER(Name)

#define ABYTEK_SRP_ECMS_DEFINE_INSTANCED_MESHLET_BUFFER_RW(Name)                                                  \
    RWStructuredBuffer<Abytek::SRP::ECMS::F_InstancedMeshlet> ABYTEK_SRP_ECMS_GET_INSTANCED_MESHLET_BUFFER(Name); \
    RWStructuredBuffer<uint> ABYTEK_SRP_ECMS_GET_INSTANCED_MESHLET_WRITE_OFFSET_BUFFER(Name)

namespace Abytek::Internal::SRP::ECMS
{
Abytek::SRP::ECMS::F_InstancedMeshletId PushInstancedMeshlet(
    RWStructuredBuffer<Abytek::SRP::ECMS::F_InstancedMeshlet> Buffer,
    RWStructuredBuffer<uint> WriteOffsetBuffer,
    in Abytek::SRP::ECMS::F_InstancedMeshlet InstancedMeshlet)
{
    uint Capacity = WriteOffsetBuffer[1];
    uint WriteOffset = Capacity;
    InterlockedAdd(
        WriteOffsetBuffer[0],
        1,
        WriteOffset);
    if (WriteOffset >= Capacity)
    {
        return Abytek::SRP::ECMS::INVALID_INSTANCED_MESHLET_ID;
    }
    Buffer[WriteOffset] = InstancedMeshlet;
    return WriteOffset;
}
Abytek::SRP::ECMS::F_InstancedMeshlet LoadInstancedMeshlet(
    StructuredBuffer<Abytek::SRP::ECMS::F_InstancedMeshlet> Buffer,
    in Abytek::SRP::ECMS::F_InstancedMeshletId InstancedMeshletId)
{
    return Buffer[InstancedMeshletId];
}
}

#define ABYTEK_SRP_ECMS_PUSH_INSTANCED_MESHLET(Name, ...)                \
    Abytek::Internal::SRP::ECMS::PushInstancedMeshlet(                   \
        ABYTEK_SRP_ECMS_GET_INSTANCED_MESHLET_BUFFER(Name),              \
        ABYTEK_SRP_ECMS_GET_INSTANCED_MESHLET_WRITE_OFFSET_BUFFER(Name), \
        __VA_ARGS__)

#define ABYTEK_SRP_ECMS_LOAD_INSTANCED_MESHLET(Name, ...)                \
    Abytek::Internal::SRP::ECMS::LoadInstancedMeshlet(                   \
        ABYTEK_SRP_ECMS_GET_INSTANCED_MESHLET_BUFFER(Name),              \
        __VA_ARGS__)
