
#include "Abytek/Base.Core.prerequisites.pch.hpp"

#ifndef ABYTEK_OBJECT_TYPEDEFS_NAMESPACE
#define ABYTEK_OBJECT_TYPEDEFS_NAMESPACE Abytek
#endif

#define ABYTEK_OBJECT_SMART_POINTER_TYPEDEFS_NAMESPACE ABYTEK_OBJECT_TYPEDEFS_NAMESPACE
#include "Abytek/ObjectSmartPointerTypedefs.inl"

#define ABYTEK_RUNTIME_CONTAINER_TYPEDEFS_NAMESPACE ABYTEK_OBJECT_TYPEDEFS_NAMESPACE
#include "Abytek/RuntimeContainerTypedefs.inl"

#define ABYTEK_OBJECT_UTILITY_TYPEDEFS_NAMESPACE ABYTEK_OBJECT_TYPEDEFS_NAMESPACE
#include "Abytek/ObjectUtilityTypedefs.inl"

#undef ABYTEK_OBJECT_TYPEDEFS_NAMESPACE